### ISSUE TITLE
Metadata for Quicklisp

### ISSUE THREAD

**Issue by hydandata** [orivej/pzmq#9]
Please consider adding :description, :author and :license information to your ASDF system. This will greatly help Quicklisp users and make it easier for them to report bugs.

More information:

http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
https://www.quicklisp.org

**Comment by orivej** [comment]
My "ASDF system" — the primary one — has :description, :author and :license information! Your implied claim that it does not is incorrect. However, its auxiliary systems had not. Now I described them too, and I hope that Xach will make his metadata gatherer a little bit more intelligent, so that it fills :author and :license of auxiliary systems automatically: http://www.reddit.com/r/lisp/comments/37bxu7/systems_in_red_dont_build_if_strict_checking_of/crr5kvy?context=10000

**Comment by hydandata** [comment]
Thank you!
